# Generated by Django 5.1.3 on 2024-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='', upload_to='images/doctors'),
            preserve_default=False,
        ),
    ]
